/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalReturnRouteImport } from './routes/legal.return'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReturnRoute = LegalReturnRouteImport.update({
  id: '/legal/return',
  path: '/legal/return',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/return': typeof LegalReturnRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/return': typeof LegalReturnRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/return': typeof LegalReturnRoute
  '/legal/terms': typeof LegalTermsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/return'
    | '/legal/terms'
    | '/services/$slug'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/return'
    | '/legal/terms'
    | '/services/$slug'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/return'
    | '/legal/terms'
    | '/services/$slug'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalReturnRoute: typeof LegalReturnRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/return': {
      id: '/legal/return'
      path: '/legal/return'
      fullPath: '/legal/return'
      preLoaderRoute: typeof LegalReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalReturnRoute: LegalReturnRoute,
  LegalTermsRoute: LegalTermsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
